### ISSUE TITLE
Infinite potion effects

### ISSUE THREAD

**Issue by TiramiFKingsuTime** [hexle-at/ItemEffects#12]
Server-Version:1.19.4-paper
Plugin-Version:1.2.1
Description:In addition to wearing items on hat, when you place items on Item Frame, it will also cause infinite potion effects.
Error:No error

**Comment by Pianist20005** [comment]
Hello thanks reporting the bug, we will check it out and provide a solution as far as we can. It will take some time, but we will keep you updated. 
Kind regards Beni

**Comment by Pianist20005** [comment]
Hey, we have good news for you! I have just fixed the bug and the update will be available in the next hours! Feel free to checkout the spigot page in some hours. Hope you enojoy the plugin!
If there is anything, just open another issue!
Best regards Beni
