### ISSUE TITLE
[Error] Commands/ Plugin not working properly

### ISSUE THREAD

**Issue by TH3N3WN00B** [hexle-at/ItemEffects#20]
Server version:
UniverseSpigot version 1.21.1-DEV-ver/1.21.1@9bef923 (2024-10-24T11:51:48Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Universe-1.21.1-DEV-9bef923 (MC: 1.21.1)

Plugin Version: 1.2.7

Description: Plugin starts and seems as functioning but when using the GUI/ Commands it doesnt work and throws the error bellow

Error: https://mclo.gs/SH9DlIZ
Log: https://mclo.gs/k5pe4AC

**Comment by Pianist20005** [comment]
Hey @TH3N3WN00B,
the issue should be resolved by now! We have released a new version with full 1.21 support!

If there is anything else, feeld free to open a ticket!
