### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by DonorKrovi** [hexle-at/ItemEffects#3]
I had a good idea for a plugin, namely the output of effects with a full set of armor! The player will get the desired effect if the armor is fully equipped of the same type!

and **CustomCrafting**- You need to add support because the armor after crafting has no set effects.

**Comment by hexle-at** [comment]
Hello, thanks for your suggestion!
Regarding the first suggestion, the effect from the armour should be applied (to the player) as soon as the player has all the same effects on every armor slot?
e.g.:
Diamond-Helmet: `glowing`
Diamond-Chestplate: `glowing, luck`
Diamond-Leggings: `glowing`
Diamond-Boots: `glowing`
Now the player will have the effect `glowing` but NOT the effect `luck` right?

Custom Crafting:
We will have a look onto this! The effects should still remain on the armor, right?

**Comment by hexle-at** [comment]
Another example (this is already working) is, when you combine to items in an anvil:
![image](https://user-images.githubusercontent.com/92221159/158078663-11dca139-0e8e-404d-b398-ff928aca7abc.png)
If you switch the first two slots from the anvil it WONT work, due to prioritization from the anvil.

If a player **crafts** any item in the workbench/crafting table which has an effect it should be applied to the "final item" right?

**Comment by hexle-at** [comment]
Okay we got the idea 👍🏽
We will make a plan for the "Armor-System". It should be easy for everyone so the players are able to configure the armor as they want to.

That's no problem at all!

**Comment by hexle-at** [comment]
Hello, your requested feature is available! You can download the latest version on spigot! We are happy about a good review!
If there are any bugs, just inform us!

-> The CustomCrafting is not available yet! It might be added in a future update!

**Comment by DonorKrovi** [comment]
> Hello, your requested feature is available! You can download the latest version on spigot! We are happy about a good review! If there are any bugs, just inform us!
> 
> -> The CustomCrafting is not available yet! It might be added in a future update!

didn't understand how to use it

**Comment by hexle-at** [comment]
Did you not understand the Armor Editor?
Just run the following command: /itemeffecter armor
-> Then a GUI will pop up and you can select if you want to edit the armor that is currently on you OR if you want to create a "new" armor. After that you can either select the armor type AND/OR the effects you want to add onto the armor.
When you see the GUI with all the potions in it, just left click a potion (multiple times is possible) to add the effect. Right click the potion to remove it (or decrease it by 1).

On the right side you can choose wether the effects are shown in the item's lore or if they are hidden (NBT).
On the left side you can decide if you want to add the effect on ALL armor pieces or if the effect will be only applied when the player has the complete armor on.

Then you can click onto the "Apply" button, to geht the armor.

Do you understand it now? We hope we could help you!

**Comment by XionioXMaster** [comment]
> Did you not understand the Armor Editor? Just run the following command: /itemeffecter armor -> Then a GUI will pop up and you can select if you want to edit the armor that is currently on you OR if you want to create a "new" armor. After that you can either select the armor type AND/OR the effects you want to add onto the armor. When you see the GUI with all the potions in it, just left click a potion (multiple times is possible) to add the effect. Right click the potion to remove it (or decrease it by 1).
> 
> On the right side you can choose wether the effects are shown in the item's lore or if they are hidden (NBT). On the left side you can decide if you want to add the effect on ALL armor pieces or if the effect will be only applied when the player has the complete armor on.
> 
> Then you can click onto the "Apply" button, to geht the armor.
> 
> Do you understand it now? We hope we could help you!

Not bad, but without ItemAdder or oxaren support it's very bad(

**Comment by hexle-at** [comment]
Our plugin currently provides to add potion effects onto any item/armor and we support some cool features.
->What is "very bad" concerning the plugin? How can we improve the plugin?

**Comment by XionioXMaster** [comment]
> Our plugin currently provides to add potion effects onto any item/armor and we support some cool features. ->What is "very bad" concerning the plugin? How can we improve the plugin?

The plugin is good, I think the translator exaggerated my expression.

You've added a great feature, but it only works on vanilla armor. And if you use custom armor itemadder or Oraxen it will not be possible to transfer effects (

**Comment by hexle-at** [comment]
Okay thanks for this feedback! This is no problem🙂 

Can you execute ``/itemeffects hiddenEffects`` after you run the command to add a "Transfer" effect?
Then you will get a list of all "hiddenEffects" (transfer/permission/effects...) which are applied to the item.

If there is no "list" or just a blue feedback message, then one of the plugins (itemadder or oraxen) removes the items NBT data or modifies it.
