### ISSUE TITLE
Transferring Effects

### ISSUE THREAD

**Issue by XionioXMaster** [hexle-at/ItemEffects#5]
There are negative effects in the game, which, in theory, should be used against some entity or player, the plugin is implemented so that we can only apply effects to ourselves. I propose to make it possible to apply an effect that, when interacting with another entity, will transfer the effect to it,
good for poisoning and other negative effects.

**Comment by hexle-at** [comment]
Thanks for your suggestion! 
We will have a closer look, if we can realize your idea! We will inform you when we have more information!

**Comment by hexle-at** [comment]
Hello, your requested feature is available! You can download the latest version on spigot! We are happy about a good review!
If there are any bugs, just inform us!
